name: Build ESP32 Project with Arduino CLI

on:
  push:
    # branches:
    #   - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install ESP32 Board Package
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Clone HomeSpan and IRremoteESP8266
      run: |
        git clone --branch ethernet https://github.com/HomeSpan/HomeSpan.git /home/runner/Arduino/libraries/HomeSpan
        git clone --branch Espressif-version-3 https://github.com/BorisKofman/IRremoteESP8266.git /home/runner/Arduino/libraries/IRremoteESP8266

    - name: Install HomeSpan Library
      run: |
        arduino-cli lib install "DHT sensor library"

    - name: Compile Sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32s3 ESP32-AirConditioner.ino